CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98 -pedantic
TARGET = identify
SOURCES = main.cpp identify.cpp Base.cpp A.cpp B.cpp C.cpp
OBJECTS = $(SOURCES:.cpp=.o)

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJECTS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS)

fclean: clean
	rm -f $(TARGET)

re: fclean all

.PHONY: all clean fclean re
